package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ckanthony/gin-mcp/pkg/convert"
)

func main() {
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: annotate-gen [flags] <dir>\n\n")
		fmt.Fprintf(os.Stderr, "Scans Go source files in <dir> for handler annotation comments\n")
		fmt.Fprintf(os.Stderr, "(@summary, @description, @tags, @operationId, @param, @return)\n")
		fmt.Fprintf(os.Stderr, "and generates annotations_gen.go with pre-built handler docs.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		flag.PrintDefaults()
	}
	outputFlag := flag.String("o", "", "Output file path (default: <dir>/annotations_gen.go)")
	flag.Parse()

	dir := "."
	if flag.NArg() > 0 {
		dir = flag.Arg(0)
	}

	dir, err := filepath.Abs(dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	// Collect all handler docs keyed by function name.
	docs := make(map[string]*convert.HandlerDoc)
	pkgName := ""

	err = filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			base := d.Name()
			if base == "vendor" || base == ".git" || base == "node_modules" || base == "testdata" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		// Skip generated files to avoid self-scanning.
		if strings.HasSuffix(path, "_gen.go") || strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil // skip unparseable files
		}

		if pkgName == "" {
			pkgName = f.Name.Name
		}

		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Doc == nil {
				continue
			}
			doc := convert.ParseAnnotationLines(fn.Doc.Text())
			// Only include if there's at least one meaningful annotation.
			if isEmptyDoc(doc) {
				continue
			}
			docs[fn.Name.Name] = doc
		}
		return nil
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error walking %s: %v\n", dir, err)
		os.Exit(1)
	}

	if len(docs) == 0 {
		fmt.Println("No annotated handlers found.")
		return
	}

	if pkgName == "" {
		pkgName = "main"
	}

	// Generate output.
	outPath := filepath.Join(dir, "annotations_gen.go")
	if *outputFlag != "" {
		outPath = *outputFlag
	}

	if err := writeGeneratedFile(outPath, pkgName, docs); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d handlers)\n", outPath, len(docs))
}

// isEmptyDoc returns true when doc carries no annotations.
func isEmptyDoc(doc *convert.HandlerDoc) bool {
	if doc == nil {
		return true
	}
	return doc.Summary == "" &&
		doc.Description == "" &&
		len(doc.Params) == 0 &&
		len(doc.Tags) == 0 &&
		doc.OperationID == "" &&
		doc.Returns == ""
}

// writeGeneratedFile writes annotations_gen.go.
func writeGeneratedFile(path, pkgName string, docs map[string]*convert.HandlerDoc) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	// Sort handler names for deterministic output.
	names := make([]string, 0, len(docs))
	for name := range docs {
		names = append(names, name)
	}
	sort.Strings(names)

	fmt.Fprintf(f, "// Code generated by annotate-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(f, "package %s\n\n", pkgName)
	fmt.Fprintf(f, `import "github.com/ckanthony/gin-mcp/pkg/convert"`+"\n\n")
	fmt.Fprintf(f, "func init() {\n")
	fmt.Fprintf(f, "\tconvert.SetGeneratedAnnotations(map[string]*convert.HandlerDoc{\n")

	for _, name := range names {
		doc := docs[name]
		fmt.Fprintf(f, "\t\t%q: {\n", name)
		if doc.Summary != "" {
			fmt.Fprintf(f, "\t\t\tSummary: %q,\n", doc.Summary)
		}
		if doc.Description != "" {
			fmt.Fprintf(f, "\t\t\tDescription: %q,\n", doc.Description)
		}
		if doc.OperationID != "" {
			fmt.Fprintf(f, "\t\t\tOperationID: %q,\n", doc.OperationID)
		}
		if doc.Returns != "" {
			fmt.Fprintf(f, "\t\t\tReturns: %q,\n", doc.Returns)
		}
		if len(doc.Params) > 0 {
			// Sort param keys for determinism.
			paramKeys := make([]string, 0, len(doc.Params))
			for k := range doc.Params {
				paramKeys = append(paramKeys, k)
			}
			sort.Strings(paramKeys)
			fmt.Fprintf(f, "\t\t\tParams: map[string]string{\n")
			for _, k := range paramKeys {
				fmt.Fprintf(f, "\t\t\t\t%q: %q,\n", k, doc.Params[k])
			}
			fmt.Fprintf(f, "\t\t\t},\n")
		}
		if len(doc.Tags) > 0 {
			fmt.Fprintf(f, "\t\t\tTags: []string{")
			for i, t := range doc.Tags {
				if i > 0 {
					fmt.Fprintf(f, ", ")
				}
				fmt.Fprintf(f, "%q", t)
			}
			fmt.Fprintf(f, "},\n")
		}
		fmt.Fprintf(f, "\t\t},\n")
	}

	fmt.Fprintf(f, "\t})\n")
	fmt.Fprintf(f, "}\n")

	return nil
}
